CREATE TABLE saeoss_pycsw_table(
    identifier TEXT PRIMARY KEY,
    dataset_name TEXT,
    typename TEXT,
    schema TEXT,
    mdsource TEXT,
    insert_date TEXT,
    xml TEXT,
    metadata TEXT,
    metadata_type TEXT,
    anytext TEXT,
    language TEXT,
    title TEXT,
    abstract TEXT,
    keywords TEXT,
    keywordstype TEXT,
    format TEXT,
    source TEXT,
    version TEXT,
    date_modified TEXT,
    type TEXT,
    wkt_geometry TEXT,
    wkb_geometry geometry(Polygon, 4326),
    title_alternate TEXT,
    doi TEXT,
    date_revision TEXT,
    date_creation TEXT,
    date_publication TEXT,
    organisation TEXT,
    securityconstraints TEXT,
    parentidentifier TEXT,
    topicategory JSON,
    resourcelanguage TEXT,
    geodescode TEXT,
    denominator TEXT,
    distancevalue TEXT,
    distanceuom TEXT,
    contacts TEXT,
    themes TEXT,
    date JSON,
    time_begin JSON,
    time_end TEXT,
    reference_date_type TEXT,
    servicetype TEXT,
    servicetypeversion TEXT,
    operation TEXT,
    couplingtype TEXT,
    operateson TEXT,
    operatesonidentifier TEXT,
    operatesonname TEXT,
    degree TEXT,
    accessconstraints TEXT,
    otherconstraints TEXT,
    classification TEXT,
    conditionapplyingtoaccessanduse TEXT,
    edition TEXT,
    lineage_statement TEXT,
    dataset_lineage TEXT,
    responsiblepartyrole TEXT,
    specificationtitle TEXT,
    specificationdate TEXT,
    specificationdatetype TEXT,
    creator TEXT,
    publisher TEXT,
    contributor TEXT,
    relation TEXT,
    platform TEXT,
    instrument TEXT,
    sensortype TEXT,
    cloudcover TEXT,
    bands TEXT,
    links TEXT,
    bounding_geojson JSON,
    crs JSON,
    equivalent_scale JSON
);

INSERT INTO saeoss_pycsw_table (
    identifier, dataset_name, typename, schema, mdsource, insert_date, xml, metadata, metadata_type, anytext,
    language, title, abstract, keywords, keywordstype, format, source, version, date_modified, type,
    wkt_geometry, wkb_geometry, title_alternate, doi, date_revision, date_creation, date_publication, organisation,
    securityconstraints, parentidentifier, topicategory, resourcelanguage, geodescode, denominator, distancevalue,
    distanceuom, date, time_begin, time_end, reference_date_type, servicetype, servicetypeversion, operation,
    couplingtype, operateson, operatesonidentifier, operatesonname, degree, accessconstraints, otherconstraints,
    classification, conditionapplyingtoaccessanduse, edition, lineage_statement, dataset_lineage,
    responsiblepartyrole, specificationtitle, specificationdate, specificationdatetype, creator, publisher,
    contributor, relation, platform, instrument, sensortype, cloudcover, bands, links, bounding_geojson,
    crs, equivalent_scale
)
SELECT
    identifier, dataset_name, typename, schema, mdsource, insert_date, xml, metadata, metadata_type, anytext,
    language, title, abstract, keywords, keywordstype, format, source, version, date_modified, type,
    wkt_geometry, wkb_geometry, title_alternate, doi, date_revision, date_creation, date_publication, organisation,
    securityconstraints, parentidentifier, topicategory, resourcelanguage, geodescode, denominator, distancevalue,
    distanceuom, date, time_begin, time_end, reference_date_type, servicetype, servicetypeversion, operation,
    couplingtype, operateson, operatesonidentifier, operatesonname, degree, accessconstraints, otherconstraints,
    classification, conditionapplyingtoaccessanduse, edition, lineage_statement, dataset_lineage,
    responsiblepartyrole, specificationtitle, specificationdate, specificationdatetype, creator, publisher,
    contributor, relation, platform, instrument, sensortype, cloudcover, bands, links, bounding_geojson,
    crs, equivalent_scale
FROM saeoss_pycsw_view;
