name: 📖 Build MKDocs And Publish To Github Pages.yml
on:
  push:
    branches:
      - main
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        #uses: BSFishy/pip-action@v1
        uses: timlinux/pip-action@v1
        with:
          packages: |
            mkdocs-material 
            qrcode
      - name: Checkout main from github
        uses: actions/checkout@v3
      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh
      - name: Deploy docs to github pages
        # This is where we get the material theme from
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Wrong
        #uses: timlinux/QGISAnimationWorkbench@main
        env:
          # Read this carefully:
          # https://github.com/marketplace/actions/deploy-mkdocs#building-with-github_token
          # The token is automatically generated by the GH Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
